export const ERR_TEXT_DEFAULT = 'Ошибка на сервере при обработке запроса!';
export const ERR_TEXT_INVALID_ID = 'Некорректный формат _id!';
export const ERR_TEXT_INVALID_DATA = 'Переданы некорректные данные!';
export const ERR_TEXT_INVALID_EMAIL_FORMAT = 'Некорректный формат электронной почты!';
export const ERR_TEXT_NOT_FOUND_BY_ID = 'По указанному _id в базе данных ничего не найдено!';
export const ERR_TEXT_NOT_FOUND_PAGE = 'Error 404! Страница не найдена!';
export const ERR_TEXT_NOT_FOUND_JWT_SECRET = 'Недействительный токен!';
export const ERR_TEXT_INVALID_TOKEN = 'Недействительный токен!';
export const ERR_TEXT_UNAUTH_ERROR = 'Неправильные почта или пароль';
